### ISSUE TITLE
How to build source of bamboo to rpm package? 

### ISSUE THREAD

**Issue by VFT** [QubitProducts/bamboo#184]
There is only build script for deb package in build.sh,How to build source of bamboo to rpm package?

because my system is centos.

**Comment by activars** [comment]
- You need to build the binary in centos
- We are using fpm(ruby gem) , fpm has an option to build rpm package. You might need to modify build.sh script

**Comment by rasputnik** [comment]
@VFT we build our RPMs by making these changes 

edit builder/build.after-install

# change the 'configure)' to '*)'

edit builder/build.sh and set:

*  'version' to '0.2.15' (or whatever release you're using)
* 'arch' to 'x86_64' (since it still links against some C libraries on our Go version)
* 'pkgtype' to 'rpm'


# one
# two
# three

**Comment by VFT** [comment]
@activars  @rasputnik thank you very mush,rpm package was created under your guidance.

**Comment by activars** [comment]
Your solution might be useful and save time for other users. Would it possible you can share and make a Pull Request about your solution?

**Comment by rasputnik** [comment]
Sure, shell isn't my thing really but it shouldn't be that hard.
