### ISSUE TITLE
default haproxy ReloadCommand locks up

### ISSUE THREAD

**Issue by c089** [QubitProducts/bamboo#79]
The haproxy reload script frequently locks up, prevent config updates for haproxy. I found two related commits: https://github.com/QubitProducts/bamboo/commit/3bf7fd5864af540fe760a558abfca5f509cd0e80 https://github.com/QubitProducts/bamboo/commit/d1d3b6588bdc0a8ea08759dd0ca05fa908d215e2

Note how the second one changes from reading the PID file to using `pidof`. On our server where the reload hangs, `pidof` reports two running haproxy processes, while there is only one PID in the file - which seems to be the issue mentioned by @sttts in the first commit. The existence of the extra PID, in combination with the `while` loop from the first commit causes updates to hang: While haproxy reloads sucessfully, the `while` will never terminate, so further updates will not trigger reloads anymore.

```
$ cat /var/run/haproxy.pid
25296
$ pidof haproxy
25296 22555
```

```
$ ps aux|grep haproxy
haproxy  22555  0.0  0.1  30512  3072 ?        Ss   09:27   0:01 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf 22492
1000     22707  0.0  0.0   9356   644 pts/2    R+   13:57   0:00 grep --color=auto haproxy
root     25293  0.3  0.0   4400   636 ?        S    10:34   0:41 sh -c PIDS=`pidof haproxy`; haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf $PIDS && while ps -p $PIDS; do sleep 0.2; done
haproxy  25296  0.0  0.1  30696  3072 ?        Ss   10:34   0:02 haproxy -f /etc/haproxy/haproxy.cfg -p /var/run/haproxy.pid -sf 22555
```

I wonder why the production.example.json was updated in that second commit (cc @activars): to me, it seems that reading the PIDs from the PID file is the correct way.

**Comment by c089** [comment]
woops I mixed up bamboo versions, it seems this server was running a version before the sync commit. I think this is exactly what stefan fixed - closing this, sorry for confusion

**Comment by c089** [comment]
...and it's back, with current bamboo master

**Comment by activars** [comment]
Which marathon version you are running with?

**Comment by c089** [comment]
0.8.0-1.1.82.RC2 seems we missed the stable release. think it's related?

**Comment by activars** [comment]
It's possible related to how http callback events are handled, which may trigger haproxy to reload more frequently than it needs.

I should have some time late this week or early next week to test Marathon 0.8. And I have some plan to improve the http callback handling.

**Comment by sttts** [comment]
I also have a Marathon 0.8.x setup running with Bamboo. And I saw blocked haproxy reloads as well. 

But I don't think much changed in the Marathon http callback api, if anything at all.

**Comment by activars** [comment]
On top of my head, haproxy reload triggers by two sources: Bamboo zk records and http callbacks from marathon. Zk records change has a fixed timeout to avoid fast reload. http callbacks are not guarded by a global timer. 

It's also possible that Bamboo should differentiate between current running Marathon tasks and those ones are under deployment.  I current see the behaviour of:
- App1 has two running/serving tasks 
- I trigger app update (scaling up or update a new version of docker image)
- Bamboo puts pending tasks into HAProxy before it's ready

I suspect the result task list for generating the template needs filtering.

**Comment by sttts** [comment]
I don't think the problem right now is any kind of missing filtering or too often reload (which is not an issue as those are sequentialized anyway in Bamboo).

What I saw was that Bamboo was not starting a new reload because the previous one had not finished yet. But this situation did not change until all haproxy tasks were killed manually.

**Comment by c089** [comment]
So far I'm not seeing this lock up anymore, but I just remember I also changed the `RelaodCommand` to use `service haproxy reload`, so that may be the fix.

**Comment by sttts** [comment]
Wondering, what was the reason not to use `service haproxy reload` in the first place? Was it only because bamboo was supposed to run in a Docker environment?

**Comment by c089** [comment]
Might be... Although I took a look at that init script in ubuntu and it seems to do pretty much the same thing, just without the while loop:

```
haproxy_reload()
{
        $HAPROXY -f "$CONFIG" -p $PIDFILE -D $EXTRAOPTS -sf $(cat $PIDFILE) \
                || return 2
        return 0
}
```

**Comment by sttts** [comment]
Does this block? I remember that one problem with bamboo was that it was triggering multiple reload calls in a short time (within the same second). This produced zombie processes. Hence, I think this `service haproxy reload` might not be enough.

**Comment by c089** [comment]
I think it doesn't block, but I just ran `while true;do service haproxy reload;sleep .2;done` for a minute and didn't get any zombie processes.

**Comment by activars** [comment]
I believe that is when Bamboo didn't diff on the output result and Marathon pings a lot of events data. We stil need to make a global timer to guard the threshold.

**Comment by sttts** [comment]
c089: how long does it take for the new haproxy process to take over?

**Comment by sttts** [comment]
I guess, when it takes longer (many many connections which must be passed to the new process), it will get problems. 

What happens when you remove the sleep from your test?

**Comment by c089** [comment]
`for i in {1..1000};do service haproxy reload;done` no problems

**Comment by sttts** [comment]
Rereading the commit msg of 3bf7fd5, I still don't have a good feeling with this. There is a race condition between the creation of the `$PIDFILE` and reading it in `$(cat $PIDFILE)` IMO. Is there any reason why this shouldn't be a race condition? 

Try to simulate it by wrapping /usr/bin/haproxy with something like `sleep 1; orig_haproxy "$@"`. I don't see why this shouldn't break.

**Comment by c089** [comment]
Good idea, that actually invalidates my previous assumption: `service haproxy relaod` _does_ block.

**Comment by c089** [comment]
Also, the thing is, even with the command from https://github.com/QubitProducts/bamboo/commit/3bf7fd5864af540fe760a558abfca5f509cd0e80 I've seen lockup behaviour :/

I'll put that one back in instead of the `service` call and see if that breaks.

**Comment by sttts** [comment]
If it blocks, that would be great. But how does it block?

**Comment by c089** [comment]
Oh damn, sorry about that - I put the sleep in the init script, _of course_ that blocks #fail So you're probably right, we need the synchronization but as I've seen the lockups with the default ReloadCommand, we might need something better.

I feel like we should raise this issue upstream...

**Comment by sttts** [comment]
I agree. there must be something missing. And in fact I would expect all this synchronization logic from the haproxy binary itself. So yes, upstream might be helpful.

**Comment by c089** [comment]
http://www.haproxy.org/knownbugs-1.3.html

a) omg what is this I can't even

b) it seems like a known issue:
> (M) old process remains present after config reload	W	W	W	W	W	W	W	W	W	W	W	W	W	W		W	W	W	W	W	W	W	W	W	W		W	W	W				

where

>  A 'W' indicates that the bug is present but a reasonable workaround is possible.

Question remains, what the reasonable workaround is ;)

**Comment by activars** [comment]
It's good you spotted this!

**Comment by activars** [comment]
Do you thin the reload operation should try to discover the locked up process and kill it?

**Comment by timoreimann** [comment]
After having digged a bit deeper into the issue, I believe that the solution should look different: There's a [related thread on the HAProxy mailing list](http://marc.info/?l=haproxy&m=140620880818099&w=2), with an explanation of the problem and some possible solutions [here](http://marc.info/?l=haproxy&m=140688302615929&w=2) and [here](http://marc.info/?l=haproxy&m=140717716425858&w=2). The bottom line is that if you trigger a restart with another restart still pending, you end up with two processes. HAProxy usually restarts fairly fast, but if you happen to have long-running connections open that keep the proxy from finishing the restart, you can easily run into a situation where a second restart is fired off and reaches HAProxy. I believe this is what @c089 and myself may be experiencing.

All proposed fixes to be problem apparently either come with caveats or are expensive to implement. The workaround mentioned seems to be sequentialization of the restarts; that is, the restarting instance has to make sure that restarts strictly happen in order. So I think Bamboo should keep track of whether a restart is still in progress and if so, hold back any planned restarts (coming in from Marathon HTTP callbacks) until the current one has finished. As a bonus, Bamboo could merge multiple pending configuration change requests into a single one, thus getting rid of unnecessary restarts.

@activars and the rest, what do you think?

**Comment by activars** [comment]
I agree on your suggested solution. It seems to be most clean and cheap to
implement.

On 13 Mar 2015, at 21:40, Timo Reimann <notifications@github.com> wrote:

After having digged a bit deeper into the issue, I believe that the
solution should look different: There's a related thread on the HAProxy
mailing list <http://marc.info/?l=haproxy&m=140620880818099&w=2>, with an
explanation of the problem and some possible solutions here
<http://marc.info/?l=haproxy&m=140688302615929&w=2> and here
<http://marc.info/?l=haproxy&m=140717716425858&w=2>. The bottom line is
that if you trigger a restart with another restart still pending, you end
up with two processes. HAProxy usually restarts fairly fast, but if you
happen to have long-running connections open that keep the proxy from
finishing the restart, you can easily run into a situation where a second
restart is fired off and reaches HAProxy. I believe this is what @c089
<https://github.com/c089> and myself may be experiencing.

All proposed fixes to be problem apparently either come with caveats or are
expensive to implement. The workaround mentioned seems to be
sequentialization of the restarts; that is, the restarting instance has to
make sure that restarts strictly happen in order. So I think Bamboo should
keep track of whether a restart is still in progress and if so, hold back
any planned restarts (coming in from Marathon HTTP callbacks) until the
current one has finished. As a bonus, Bamboo could merge multiple pending
configuration change requests into a single one, thus getting rid of
unnecessary restarts.

@activars <https://github.com/activars> and the rest, what do you think?

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/issues/79#issuecomment-79437238>.

**Comment by sttts** [comment]
What @timoreimann proposes is exactly what my old, merged pr #33 implemented.

**Comment by timoreimann** [comment]
In that case, the issue at hand is either completed unrelated to the one that @sttts fixed via #33, or it's missing some edge case. (Having looked at the code yet though, so just guessing wildly.)

**Comment by timoreimann** [comment]
On the question of whether to read out the PIDs from the pidfile or via `pidof`: I actually think that `pidof` is the better approach for two reasons.

First, the content of the pidfile may not be correct (I managed to get it into a bad state when messing around with HAProxy), so querying the process table as the authoritative source of truth seems more reliable.

And second, pidfiles are not guaranteed to be used under all circumstances. Looking at the HAProxy code, you can tell that the pidfile is only written either when running in daemon mode (`-D` switch) or when HAProxy is spawned via systemd. In all other cases, the pidfile is ignored. Relevant code section from `src/haproxy.c`:

```c
/* open log & pid files before the chroot */
if (global.mode & (MODE_DAEMON | MODE_SYSTEMD) && global.pidfile != NULL) {
    unlink(global.pidfile);
    pidfd = open(global.pidfile, O_CREAT | O_WRONLY | O_TRUNC, 0644);
    if (pidfd < 0) {
        Alert("[%s.main()] Cannot create pidfile %s\n", argv[0], global.pidfile);
        if (nb_oldpids)
            tell_old_pids(SIGTTIN);
        protocol_unbind_all();
        exit(1);
    }
}
```

**Comment by activars** [comment]
I kind of prefer the restart queue is managed by Go code (slightly managed).

On 15 March 2015 at 01:33, Timo Reimann <notifications@github.com> wrote:

> On the question of whether to read out the PIDs from the pidfile or via
> pidof: I actually think that pidof is the better approach for two reasons.
>
> First, the content of the pidfile may not be correct (I managed to get it
> into a bad state when messing around with HAProxy), so querying the process
> table as the authoritative source of truth seems more reliable.
>
> And second, pidfiles are not guaranteed to be used under all
> circumstances. Looking at the HAProxy code, you can tell that the pidfile
> is only written either when running in daemon mode (-D switch) or when
> HAProxy is spawned via systemd. In all other cases, the pidfile is ignored.
> Relevant code section from src/haproxy.c:
>
> /* open log & pid files before the chroot */if (global.mode & (MODE_DAEMON | MODE_SYSTEMD) && global.pidfile != NULL) {
>     unlink(global.pidfile);
>     pidfd = open(global.pidfile, O_CREAT | O_WRONLY | O_TRUNC, 0644);
>     if (pidfd < 0) {
>         Alert("[%s.main()] Cannot create pidfile %s\n", argv[0], global.pidfile);
>         if (nb_oldpids)
>             tell_old_pids(SIGTTIN);
>         protocol_unbind_all();
>         exit(1);
>     }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QubitProducts/bamboo/issues/79#issuecomment-80792522>.
>



-- 
This email may be confidential or privileged. If you received this
communication
by mistake, please don't forward it to anyone else, please erase all copies
and attachments, and please let me know that it has gone the wrong person.
Thanks.

**Comment by timoreimann** [comment]
I invested a bit more time into the issue, and I think I found the reason why @c089 and me ran into those lockups: Basically, one must not use `pidof haproxy` to determine the PID of the old process that is to release the port during a hot reconfiguration (i.e., `-sf`/`-st`switch used). This works well most of the time when there are no long-running connections as the hand-over period will be very short. However, in the case of long-running connections, follow-up restarts triggering `pidof haproxy` will catch the PID of the first HAProxy process still running, thus breaking proper chaining of multiple restart commands.

There's a great example on how this can go wrong in [this Marathon mailing list posting](https://groups.google.com/d/msg/marathon-framework/R6RkBHaFtBo/yoXbjuih3pAJ) by [Evan Krall](https://github.com/EvanKrall). In a nutshell, for an originating HAProxy process A to be taken over via hot reconfiguration, its PID must be passed to the `-sf` switch of a newer process B, whose PID must be passed to the `sf` switch of an even newer process C, and so on. When you pass both A's and B's PIDs to the restart command for C, things will go wrong and you end up with more than one HAProxy instance running (even after all connections are closed).

I will follow up with a PR to fix the erroneous example in [config/production.example.json](https://github.com/QubitProducts/bamboo/blob/6f22fdd2442fe76898ccd833424b55f21f52acaa/config/production.example.json#L18). However, that's not enough because [the other two restart commands available on the project](https://github.com/QubitProducts/bamboo/search?q=read+PIDS+%3C+%2Fvar%2Frun%2Fhaproxy.pid&type=Code&utf8=%E2%9C%93) reading from the pidfile do not specify the `-D` parameter to daemonize HAProxy. As explained in a [previous comment of mine](https://github.com/QubitProducts/bamboo/issues/79#issuecomment-80792522), this can be an issue for non-systemd environments where the pidfile is not written unless daemon mode is enabled. I will also fix that in my PR.

What's left to decide then is whether we need more synchronization. From what I understood, Bamboo already takes care of serializing and synchronizing consecutive restart commands, which makes me believe that Bamboo users should be fine and we can close this ticket with my future PR. Just to be sure, I will update our Bamboo restart command and let it run for a while. Our staging environment has gotten a lot more crowdy since this issue was created, so chances are we will run into any concurrency issues.

**Comment by activars** [comment]
Great findings!
I was looking into this today as well, also reduce/avoid the connection
drop when reload happens. Could you make the PR and I will run some
workload to see if the situation is improved.




On 24 Apr 2015, at 19:11, Timo Reimann <notifications@github.com> wrote:

I invested a bit more time into the issue, and I think I found the reason
why @c089 <https://github.com/c089> and me ran into those lockups:
Basically, one must not use pidof haproxy to determine the PID of the old
process that is to release the port during a hot reconfiguration (i.e., -sf/
-stswitch used). This works well most of the time when there are no
long-running connections as the hand-over period will be very short.
However, in the case of long-running connections, follow-up restarts
triggering pidof haproxy will catch the PID of the first HAProxy process
still running, thus breaking proper chaining of multiple restart commands.

There's a great example on how this can go wrong in this Marathon mailing
list posting
<https://groups.google.com/d/msg/marathon-framework/R6RkBHaFtBo/yoXbjuih3pAJ>
by Evan Krall <https://github.com/EvanKrall>. In a nutshell, for an
originating HAProxy process A to be taken over via hot reconfiguration, its
PID must be passed to the -sf switch of a newer process B, whose PID must
be passed to the sf switch of an even newer process C, and so on. When you
pass both A's and B's PIDs to the restart command for C, things will go
wrong and you end up with more than one HAProxy instance running (even
after all connections are closed).

I will follow up with a PR to fix the erroneous example in
config/production.example.json
<https://github.com/QubitProducts/bamboo/blob/6f22fdd2442fe76898ccd833424b55f21f52acaa/config/production.example.json#L18>.
However, that's not enough because the other two restart commands available
on the project
<https://github.com/QubitProducts/bamboo/search?q=read+PIDS+%3C+%2Fvar%2Frun%2Fhaproxy.pid&type=Code&utf8=%E2%9C%93>
reading from the pidfile do not specify the -D parameter to daemonize
HAProxy. As explained in a previous comment of mine
<https://github.com/QubitProducts/bamboo/issues/79#issuecomment-80792522>,
this can be an issue for non-systemd environments where the pidfile is not
written unless daemon mode is enabled. I will also fix that in my PR.

What's left to decide then is whether we need more synchronization. From
what I understood, Bamboo already takes care of serializing and
synchronizing consecutive restart commands, which makes me believe that
Bamboo users should be fine and we can close this ticket with my future PR.
Just to be sure, I will update our Bamboo restart command and let it run
for a while. Our staging environment has gotten a lot more crowdy since
this issue was created, so chances are we will run into any concurrency
issues.

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/issues/79#issuecomment-96018815>.

**Comment by activars** [comment]
it would be good to know haproxy version you tested against. I think
current 1.5.11 has differs behaviour when restart or reload.

There should be a fast reload option.

On 24 Apr 2015, at 19:11, Timo Reimann <notifications@github.com> wrote:

I invested a bit more time into the issue, and I think I found the reason
why @c089 <https://github.com/c089> and me ran into those lockups:
Basically, one must not use pidof haproxy to determine the PID of the old
process that is to release the port during a hot reconfiguration (i.e., -sf/
-stswitch used). This works well most of the time when there are no
long-running connections as the hand-over period will be very short.
However, in the case of long-running connections, follow-up restarts
triggering pidof haproxy will catch the PID of the first HAProxy process
still running, thus breaking proper chaining of multiple restart commands.

There's a great example on how this can go wrong in this Marathon mailing
list posting
<https://groups.google.com/d/msg/marathon-framework/R6RkBHaFtBo/yoXbjuih3pAJ>
by Evan Krall <https://github.com/EvanKrall>. In a nutshell, for an
originating HAProxy process A to be taken over via hot reconfiguration, its
PID must be passed to the -sf switch of a newer process B, whose PID must
be passed to the sf switch of an even newer process C, and so on. When you
pass both A's and B's PIDs to the restart command for C, things will go
wrong and you end up with more than one HAProxy instance running (even
after all connections are closed).

I will follow up with a PR to fix the erroneous example in
config/production.example.json
<https://github.com/QubitProducts/bamboo/blob/6f22fdd2442fe76898ccd833424b55f21f52acaa/config/production.example.json#L18>.
However, that's not enough because the other two restart commands available
on the project
<https://github.com/QubitProducts/bamboo/search?q=read+PIDS+%3C+%2Fvar%2Frun%2Fhaproxy.pid&type=Code&utf8=%E2%9C%93>
reading from the pidfile do not specify the -D parameter to daemonize
HAProxy. As explained in a previous comment of mine
<https://github.com/QubitProducts/bamboo/issues/79#issuecomment-80792522>,
this can be an issue for non-systemd environments where the pidfile is not
written unless daemon mode is enabled. I will also fix that in my PR.

What's left to decide then is whether we need more synchronization. From
what I understood, Bamboo already takes care of serializing and
synchronizing consecutive restart commands, which makes me believe that
Bamboo users should be fine and we can close this ticket with my future PR.
Just to be sure, I will update our Bamboo restart command and let it run
for a while. Our staging environment has gotten a lot more crowdy since
this issue was created, so chances are we will run into any concurrency
issues.

—
Reply to this email directly or view it on GitHub
<https://github.com/QubitProducts/bamboo/issues/79#issuecomment-96018815>.

**Comment by timoreimann** [comment]
We use 1.5.11. The hot reconfiguration option has been available in HAProxy since 1.2: http://www.haproxy.org/download/1.2/doc/haproxy-en.txt

Did you mean that one, or something different?

I couldn't manage to do the PR on Friday; will try to finish things over the weekend, on Monday at the latest. It's not a big thing code-wise but I'd like to document all my findings properly.

Thanks!

**Comment by activars** [comment]
Thanks, no rush at all.

On 25 April 2015 at 18:07, Timo Reimann <notifications@github.com> wrote:

> We use 1.5.11. The hot reconfiguration option has been available in
> HAProxy since 1.2: http://www.haproxy.org/download/1.2/doc/haproxy-en.txt
>
> Did you mean that one, or something different?
>
> I couldn't manage to do the PR on Friday; will try to finish things over
> the weekend, on Monday at the latest. It's not a big thing code-wise but
> I'd like to document all my findings properly.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/QubitProducts/bamboo/issues/79#issuecomment-96237462>.
>



-- 
This email may be confidential or privileged. If you received this
communication
by mistake, please don't forward it to anyone else, please erase all copies
and attachments, and please let me know that it has gone the wrong person.
Thanks.

**Comment by activars** [comment]
I'm closing this issue by #122. Please create a new issue and reference to this one if you see it happen.
