### ISSUE TITLE
Allow creating entries using PUT

### ISSUE THREAD

**Issue by c089** [QubitProducts/bamboo#81]
Currently, to get a "create or update" behaviour, clients have to implement it themselves, because POSTing with an existing id will fail, as will putting with a non-existing id. It would be convenient if PUT could be used for creating new configurations too.

**Comment by activars** [comment]
I'm working on this.

**Comment by activars** [comment]
how about allowing creating and updating entry using POST?

**Comment by c089** [comment]
Why would you want to use POST instead of PUT for this?

**Comment by activars** [comment]
I checked with Marathon guys, they keep creating new app feature in PUT (used to work with POST, but they deprecated in 0.8.1). I will keep it consistent with Marathon allowing PUT to create new record.  Ignore my previous comment. :)

A working solution should available by end the week.

**Comment by c089** [comment]
:+1: thanks for your wor

**Comment by activars** [comment]
I'm also improving API URL encoding #58 issue together with this. 
So you should be able to PUT `/api/services/{marathon-app-id}` without escaping the Marathon App ID.

It turns out the internal webserver goji changes HTTP behaviour when URL has double '//' by forcing 301 redirect and losing HTTP body (I don't like this...). I'm considering moving to other webservers, hopefully it's not too much work involved.

**Comment by activars** [comment]
Closed by #109 
Bamboo's API URI requirement has changed, you don't need to encode Marathon AppId Anymore.
